<?php

return [
    'SY' => [
        'name' => 'Short Yardage',
        'roll' => [
            '20-22' => [
                'player' => 'LB2',
                'rating' => 'TACKLE',
                'skill_pass' => '-5',
                'skill_fail' => '-1',
            ],
            '23-24' => [
                'player' => 'LB4',
                'rating' => 'TACKLE',
                'skill_pass' => '-5',
                'skill_fail' => '0',
            ],
            '25-26' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '-3',
                'skill_fail' => '1',
            ],
            '27-28' => [
                'player' => 'CB1',
                'rating' => 'TACKLE',
                'skill_pass' => '0',
                'skill_fail' => '6',
            ],
            '29' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '-1',
                'skill_fail' => '5',
            ],
            '30-32' => [
                'player' => 'CB1',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '8',
            ],
            '33-34' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '9',
            ],
            '35-37' => [
                'player' => 'OL',
                'rating' => 'RUSH',
                'skill_pass' => '7',
                'skill_fail' => '-1',
            ],
            '38-39' => [
                'player' => 'LB4',
                'rating' => 'TACKLE',
                'skill_pass' => '-6',
                'skill_fail' => 'B!',
            ],
            '40-42' => [
                'player' => 'CB1',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '13',
            ],
            '43-44' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '14',
            ],
            '45-47' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '5',
                'skill_fail' => 'B!',
            ],
            '48-49' => [
                'player' => 'S2',
                'rating' => 'TACKLE',
                'skill_pass' => '6',
                'skill_fail' => 'B!',
            ],
            '50-51' => [
                'player' => 'S2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '10 + B!',
            ],
            '52-53' => [
                'player' => 'S1',
                'rating' => 'SACK',
                'skill_pass' => 'SK 6',
                'skill_fail' => 'B!',
            ],
            '54' => [
                'player' => 'WR2',
                'rating' => 'REC',
                'skill_pass' => '10 + B!',
                'skill_fail' => 'INC',
            ],
            '55-57' => [
                'player' => 'WR4',
                'rating' => 'DEEP',
                'skill_pass' => '20 + B!',
                'skill_fail' => '16',
            ],
            '58-59' => [
                'player' => 'WR3',
                'rating' => 'DEEP',
                'skill_pass' => '20 + B!',
                'skill_fail' => '17',
            ],
            '60-62' => [
                'player' => 'WR4',
                'rating' => 'DEEP',
                'skill_pass' => '30 + B!',
                'skill_fail' => '26',
            ],
            '63-64' => [
                'player' => 'WR1',
                'rating' => 'DEEP',
                'skill_pass' => '30 + B!',
                'skill_fail' => '23',
            ],
        ]
    ],
    'RC' => [
        'name' => 'Rush Contain',
        'roll' => [
            '20-22' => [
                'player' => 'LB4',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '7',
            ],
            '23-24' => [
                'player' => 'OL',
                'rating' => 'POWER',
                'skill_pass' => '5',
                'skill_fail' => '1',
            ],
            '25-26' => [
                'player' => 'S1',
                'rating' => 'TACKLE',
                'skill_pass' => '0',
                'skill_fail' => '4',
            ],
            '27-28' => [
                'player' => 'LB4',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '6',
            ],
            '29' => [
                'player' => 'LB3',
                'rating' => 'TACKLE',
                'skill_pass' => '-2',
                'skill_fail' => '3',
            ],
            '30-32' => [
                'player' => 'DL3',
                'rating' => 'TACKLE',
                'skill_pass' => '-6',
                'skill_fail' => '1',
            ],
            '33-34' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '-6',
                'skill_fail' => '1',
            ],
            '35-37' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '-3',
                'skill_fail' => '2',
            ],
            '38-39' => [
                'player' => 'LB2',
                'rating' => 'TACKLE',
                'skill_pass' => '-2',
                'skill_fail' => '3',
            ],
            '40-42' => [
                'player' => 'CB1',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '8',
            ],
            '43-44' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '9',
            ],
            '45-47' => [
                'player' => 'S1',
                'rating' => 'TACKLE',
                'skill_pass' => '8',
                'skill_fail' => 'B!',
            ],
            '48-49' => [
                'player' => 'S2',
                'rating' => 'TACKLE',
                'skill_pass' => '7',
                'skill_fail' => 'B!',
            ],
            '50-51' => [
                'player' => 'S1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '11',
            ],
            '52-53' => [
                'player' => 'S2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '13',
            ],
            '54' => [
                'player' => 'LB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '10',
            ],
            '55-57' => [
                'player' => 'TE1',
                'rating' => 'DEEP',
                'skill_pass' => '20 + B!',
                'skill_fail' => '14',
            ],
            '58-59' => [
                'player' => 'TE2',
                'rating' => 'DEEP',
                'skill_pass' => '20 + B!',
                'skill_fail' => '15',
            ],
            '60-62' => [
                'player' => 'WR4',
                'rating' => 'DEEP',
                'skill_pass' => '30 + B!',
                'skill_fail' => 'INC',
            ],
            '63-64' => [
                'player' => 'WR1',
                'rating' => 'DEEP',
                'skill_pass' => '30 + B!',
                'skill_fail' => 'INC',
            ],
        ]
    ],
    'BA' => [
        'name' => 'Balanced Attack',
        'roll' => [
            '20-22' => [
                'player' => 'DL2',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '7',
            ],
            '23-24' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '9',
            ],
            '25-26' => [
                'player' => 'Dl2',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '6',
            ],
            '27-28' => [
                'player' => 'RB1',
                'rating' => 'RUSH',
                'skill_pass' => '13',
                'skill_fail' => '3',
            ],
            '29' => [
                'player' => 'S1',
                'rating' => 'TACKLE',
                'skill_pass' => '5',
                'skill_fail' => '10',
            ],
            '30-32' => [
                'player' => 'LB3',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '9',
            ],
            '33-34' => [
                'player' => 'LB3',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '9',
            ],
            '35-37' => [
                'player' => 'RB2',
                'rating' => 'RUSH',
                'skill_pass' => '14',
                'skill_fail' => '4',
            ],
            '38-39' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '-2',
                'skill_fail' => '3',
            ],
            '40-42' => [
                'player' => 'CB1',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '8',
            ],
            '43-44' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '9',
            ],
            '45-47' => [
                'player' => 'LB1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '7',
            ],
            '48-49' => [
                'player' => 'LB4',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '14',
            ],
            '50-51' => [
                'player' => 'LB3',
                'rating' => 'SACK',
                'skill_pass' => 'SK 6',
                'skill_fail' => '11',
            ],
            '52-53' => [
                'player' => 'LB4',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '10 + B!',
            ],
            '54' => [
                'player' => 'CB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '15',
            ],
            '55-57' => [
                'player' => 'DL1',
                'rating' => 'SACK',
                'skill_pass' => 'SK 5',
                'skill_fail' => '19',
            ],
            '58-59' => [
                'player' => 'CB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '21',
            ],
            '60-62' => [
                'player' => 'S2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '32',
            ],
            '63-64' => [
                'player' => 'QB1',
                'rating' => 'DEEP',
                'skill_pass' => '30 + B!',
                'skill_fail' => 'INC',
            ],
        ]

    ],
    'BR' => [
        'name' => 'Bump and Run',
        'roll' => [
            '20-22' => [
                'player' => 'DL2',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '13',
            ],
            '23-24' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '14',
            ],
            '25-26' => [
                'player' => 'Dl1',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '12',
            ],
            '27-28' => [
                'player' => 'DL3',
                'rating' => 'TACKLE',
                'skill_pass' => '6',
                'skill_fail' => '15',
            ],
            '29' => [
                'player' => 'S1',
                'rating' => 'TACKLE',
                'skill_pass' => '7',
                'skill_fail' => '17',
            ],
            '30-32' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '14',
            ],
            '33-34' => [
                'player' => 'DL3',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '11',
            ],
            '35-37' => [
                'player' => 'RB3',
                'rating' => 'RUSH',
                'skill_pass' => '17',
                'skill_fail' => '7',
            ],
            '38-39' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '5',
                'skill_fail' => '15',
            ],
            '40-42' => [
                'player' => 'CB1',
                'rating' => 'INT',
                'skill_pass' => 'INT -1',
                'skill_fail' => 'INC',
            ],
            '43-44' => [
                'player' => 'CB2',
                'rating' => 'INT',
                'skill_pass' => 'INT -3',
                'skill_fail' => 'INC',
            ],
            '45-47' => [
                'player' => 'LB2',
                'rating' => 'INT',
                'skill_pass' => 'INT 7',
                'skill_fail' => '12',
            ],
            '48-49' => [
                'player' => 'LB1',
                'rating' => 'INT',
                'skill_pass' => 'INT 5',
                'skill_fail' => '10',
            ],
            '50-51' => [
                'player' => 'CB1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '20 + B!',
            ],
            '52-53' => [
                'player' => 'LB3',
                'rating' => 'INT',
                'skill_pass' => 'INT 8',
                'skill_fail' => '13',
            ],
            '54' => [
                'player' => 'CB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '20 + B!',
            ],
            '55-57' => [
                'player' => 'S1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '20 + B!',
            ],
            '58-59' => [
                'player' => 'S2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '20 + B!',
            ],
            '60-62' => [
                'player' => 'WR4',
                'rating' => 'DEEP',
                'skill_pass' => '30 + B!',
                'skill_fail' => 'INC',
            ],
            '63-64' => [
                'player' => 'QB1',
                'rating' => 'DEEP',
                'skill_pass' => '30 + B!',
                'skill_fail' => 'INC',
            ],
        ]
    ],
    'SZ' => [
        'name' => 'Short Zone',
        'roll' => [
            '20-22' => [
                'player' => 'DL2',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '9',
            ],
            '23-24' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '7',
                'skill_fail' => '13',
            ],
            '25-26' => [
                'player' => 'Dl3',
                'rating' => 'TACKLE',
                'skill_pass' => '6',
                'skill_fail' => '11',
            ],
            '27-28' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '8',
            ],
            '29' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '7',
                'skill_fail' => '12',
            ],
            '30-32' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '8',
            ],
            '33-34' => [
                'player' => 'DL3',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '10',
            ],
            '35-37' => [
                'player' => 'RB1',
                'rating' => 'RUSH',
                'skill_pass' => '13',
                'skill_fail' => '3',
            ],
            '38-39' => [
                'player' => 'RB2',
                'rating' => 'RUSH',
                'skill_pass' => '14',
                'skill_fail' => '4',
            ],
            '40-42' => [
                'player' => 'CB1',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '8',
            ],
            '43-44' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '7',
            ],
            '45-47' => [
                'player' => 'CB2',
                'rating' => 'INT',
                'skill_pass' => 'INT 6',
                'skill_fail' => '9',
            ],
            '48-49' => [
                'player' => 'CB1',
                'rating' => 'INt',
                'skill_pass' => 'INT 4',
                'skill_fail' => '7',
            ],
            '50-51' => [
                'player' => 'LB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '10',
            ],
            '52-53' => [
                'player' => 'LB3',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '12',
            ],
            '54' => [
                'player' => 'LB4',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '13',
            ],
            '55-57' => [
                'player' => 'S1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '20 + B!',
            ],
            '58-59' => [
                'player' => 'S2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '23',
            ],
            '60-62' => [
                'player' => 'S1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '30 + B!',
            ],
            '63-64' => [
                'player' => 'S2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '30 + B!',
            ],
        ]
    ],
    'PB' => [
        'name' => 'Pass Blitz',
        'roll' => [
            '20-22' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '7',
            ],
            '23-24' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '-2',
                'skill_fail' => '6',
            ],
            '25-26' => [
                'player' => 'Dl2',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '11',
            ],
            '27-28' => [
                'player' => 'DL3',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '14',
            ],
            '29' => [
                'player' => 'S2',
                'rating' => 'TACKLE',
                'skill_pass' => '10',
                'skill_fail' => '10 + B!',
            ],
            '30-32' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '-1',
                'skill_fail' => 'B!',
            ],
            '33-34' => [
                'player' => 'RB1',
                'rating' => 'RUSH',
                'skill_pass' => '13',
                'skill_fail' => '-3',
            ],
            '35-37' => [
                'player' => 'RB2',
                'rating' => 'RUSH',
                'skill_pass' => '19',
                'skill_fail' => '9',
            ],
            '38-39' => [
                'player' => 'RB3',
                'rating' => 'RUSH',
                'skill_pass' => '22',
                'skill_fail' => '12',
            ],
            '40-42' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '9',
                'skill_fail' => '10 + B!',
            ],
            '43-44' => [
                'player' => 'CB1',
                'rating' => 'TACKLE',
                'skill_pass' => '8',
                'skill_fail' => '10 + B!',
            ],
            '45-47' => [
                'player' => 'QB1',
                'rating' => 'RUSH',
                'skill_pass' => '9',
                'skill_fail' => 'SK 3',
            ],
            '48-49' => [
                'player' => 'S1',
                'rating' => 'SACK',
                'skill_pass' => 'SK 7',
                'skill_fail' => '10',
            ],
            '50-51' => [
                'player' => 'QB1',
                'rating' => 'CTRL',
                'skill_pass' => '10 + B!',
                'skill_fail' => 'INT 12',
            ],
            '52-53' => [
                'player' => 'LB2',
                'rating' => 'SACK',
                'skill_pass' => 'SK 8',
                'skill_fail' => '14',
            ],
            '54' => [
                'player' => 'LB1',
                'rating' => 'SACK',
                'skill_pass' => 'SK 6',
                'skill_fail' => '10 + B!',
            ],
            '55-57' => [
                'player' => 'QB1',
                'rating' => 'EVADE',
                'skill_pass' => 'INC',
                'skill_fail' => 'SK 9',
            ],
            '58-59' => [
                'player' => 'LB4',
                'rating' => 'SACK',
                'skill_pass' => 'SK 5',
                'skill_fail' => '15',
            ],
            '60-62' => [
                'player' => 'S2',
                'rating' => 'INT',
                'skill_pass' => 'INT 28',
                'skill_fail' => '20 + B!',
            ],
            '63-64' => [
                'player' => 'DL2',
                'rating' => 'SACK',
                'skill_pass' => 'SK 10',
                'skill_fail' => 'INC',
            ],
        ]
    ],
    'DZ' => [
        'name' => 'Deep Zone',
        'roll' => [
            '20-22' => [
                'player' => 'RB1',
                'rating' => 'RUSH',
                'skill_pass' => 'B!',
                'skill_fail' => '4',
            ],
            '23-24' => [
                'player' => 'RB2',
                'rating' => 'RUSH',
                'skill_pass' => '15',
                'skill_fail' => '5',
            ],
            '25-26' => [
                'player' => 'Dl2',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '12',
            ],
            '27-28' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '13',
            ],
            '29' => [
                'player' => 'RB3',
                'rating' => 'RUSH',
                'skill_pass' => 'B!',
                'skill_fail' => '9',
            ],
            '30-32' => [
                'player' => 'RB2',
                'rating' => 'RUSH',
                'skill_pass' => 'B!',
                'skill_fail' => '6',
            ],
            '33-34' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '11',
            ],
            '35-37' => [
                'player' => 'LB2',
                'rating' => 'TACKLE',
                'skill_pass' => '6',
                'skill_fail' => '16',
            ],
            '38-39' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '8',
                'skill_fail' => '18',
            ],
            '40-42' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '7',
                'skill_fail' => '17',
            ],
            '43-44' => [
                'player' => 'LB2',
                'rating' => 'TACKLE',
                'skill_pass' => '6',
                'skill_fail' => '16',
            ],
            '45-47' => [
                'player' => 'LB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '12',
            ],
            '48-49' => [
                'player' => 'LB4',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '14',
            ],
            '50-51' => [
                'player' => 'TE1',
                'rating' => 'REC',
                'skill_pass' => 'B!',
                'skill_fail' => 'INC',
            ],
            '52-53' => [
                'player' => 'LB3',
                'rating' => 'COVER',
                'skill_pass' => 'SK 7',
                'skill_fail' => '13',
            ],
            '54' => [
                'player' => 'LB1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '11',
            ],
            '55-57' => [
                'player' => 'CB1',
                'rating' => 'COVER',
                'skill_pass' => 'SK 5',
                'skill_fail' => 'INC',
            ],
            '58-59' => [
                'player' => 'CB2',
                'rating' => 'INT',
                'skill_pass' => 'INT 14',
                'skill_fail' => 'INC',
            ],
            '60-62' => [
                'player' => 'S1',
                'rating' => 'INT',
                'skill_pass' => 'INT 27',
                'skill_fail' => 'INC',
            ],
            '63-64' => [
                'player' => 'S2',
                'rating' => 'INT',
                'skill_pass' => 'INT 32',
                'skill_fail' => 'INC',
            ],
        ]
    ],

];
