<?php

return [
    'IR' => [
        'name' => 'Inside Run',
        'play_type' => 'RUN',
        'roll' => [
            '10' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '5',
                'skill_fail' => 'False Start',
            ],
            '11-12' => [
                'player' => 'QB1',
                'rating' => 'RUSH',
                'skill_pass' => '5 + R',
                'skill_fail' => '1',
            ],
            '13-15' => [
                'player' => 'RB1',
                'rating' => 'RUSH',
                'skill_pass' => '3 + R',
                'skill_fail' => '2',
            ],
            '16-17' => [
                'player' => 'OL',
                'rating' => 'RUSH',
                'skill_pass' => '7',
                'skill_fail' => '2',
            ],
            '18-19' => [
                'player' => 'OL',
                'rating' => 'RUSH',
                'skill_pass' => 'B!',
                'skill_fail' => '3',
            ],
            '20-29' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '30-34' => [
                'player' => 'RB1',
                'rating' => 'POWER',
                'skill_pass' => '2 + R',
                'skill_fail' => '0',
            ],
            '35-36' => [
                'player' => 'RB2',
                'rating' => 'POWER',
                'skill_pass' => '3 + R',
                'skill_fail' => '1',
            ],
            '37-38' => [
                'player' => 'RB3',
                'rating' => 'POWER',
                'skill_pass' => '4 + R',
                'skill_fail' => '-1',
            ],
            '39-41' => [
                'player' => 'OL',
                'rating' => 'POWER',
                'skill_pass' => '3',
                'skill_fail' => '0',
            ],
            '42-45' => [
                'player' => 'OL',
                'rating' => 'POWER',
                'skill_pass' => '5',
                'skill_fail' => '1',
            ],
            '46-49' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '-2',
                'skill_fail' => '3',
            ],
            '50-53' => [
                'player' => 'DL2',
                'rating' => 'TACKLE',
                'skill_pass' => '0',
                'skill_fail' => '4',
            ],
            '54-56' => [
                'player' => 'DL3',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '6',
            ],
            '57-58' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '8',
            ],
            '59-60' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => 'B!',
            ],
            '61-62' => [
                'player' => 'LB2',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => 'B!',
            ],
            '63' => [
                'player' => 'LB3',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => 'B!',
            ],
            '64' => [
                'player' => 'S1',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '11',
            ],
            '65-68' => [
                'player' => 'AUTO',
                'rating' => 'REDZONE',
                'skill_pass' => '4',
                'skill_fail' => '0',
            ],
            '69' => [
                'player' => 'AUTO',
                'rating' => 'HOME',
                'skill_pass' => '8',
                'skill_fail' => '1',
            ],
        ]
    ],
    'OR' => [
        'name' => 'Outside Run',
        'play_type' => 'RUN',
        'roll' => [
            '10' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '5',
                'skill_fail' => 'False Start',
            ],
            '11-15' => [
                'player' => 'RB1',
                'rating' => 'RUSH',
                'skill_pass' => '5 + R',
                'skill_fail' => '0',
            ],
            '16' => [
                'player' => 'RB4',
                'rating' => 'RUSH',
                'skill_pass' => '4 + R',
                'skill_fail' => '-1',
            ],
            '17-20' => [
                'player' => 'OL',
                'rating' => 'RUSH',
                'skill_pass' => 'B!',
                'skill_fail' => '0',
            ],
            '21-24' => [
                'player' => 'OL',
                'rating' => 'RUSH',
                'skill_pass' => '5',
                'skill_fail' => '-2',
            ],
            '25-34' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '35-38' => [
                'player' => 'RB2',
                'rating' => 'RUSH',
                'skill_pass' => '6 + R',
                'skill_fail' => '0',
            ],
            '39-40' => [
                'player' => 'RB2',
                'rating' => 'RUSH',
                'skill_pass' => '2 + R',
                'skill_fail' => '1',
            ],
            '41-42' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => 'B!',
            ],
            '43-44' => [
                'player' => 'DL2',
                'rating' => 'TACKLE',
                'skill_pass' => '-3',
                'skill_fail' => '3',
            ],
            '45-46' => [
                'player' => 'DL3',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => 'B!',
            ],
            '47-48' => [
                'player' => 'DL4',
                'rating' => 'TACKLE',
                'skill_pass' => '0',
                'skill_fail' => '5',
            ],
            '49-51' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '-4',
                'skill_fail' => '2',
            ],
            '52-54' => [
                'player' => 'LB2',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '7',
            ],
            '55-57' => [
                'player' => 'LB3',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '12',
            ],
            '58-59' => [
                'player' => 'LB4',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '10',
            ],
            '60-62' => [
                'player' => 'S1',
                'rating' => 'TACKLE',
                'skill_pass' => '-1',
                'skill_fail' => '5',
            ],
            '63' => [
                'player' => 'S2',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => '13',
            ],
            '64' => [
                'player' => 'LB1',
                'rating' => 'STRIP',
                'skill_pass' => 'FF 2',
                'skill_fail' => '4',
            ],
            '65-68' => [
                'player' => 'AUTO',
                'rating' => 'REDZONE',
                'skill_pass' => '6',
                'skill_fail' => '1',
            ],
            '69' => [
                'player' => 'AUTO',
                'rating' => 'HOME',
                'skill_pass' => '10',
                'skill_fail' => '3',
            ],
        ]
    ],
    'DP' => [
        'name' => 'Draw Play',
        'play_type' => 'RUN',
        'roll' => [
            '10' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '5',
                'skill_fail' => 'False Start',
            ],
            '11-17' => [
                'player' => 'RB1',
                'rating' => 'RUSH',
                'skill_pass' => '6 + R',
                'skill_fail' => '-3',
            ],
            '18-21' => [
                'player' => 'RB2',
                'rating' => 'RUSH',
                'skill_pass' => '3 + R',
                'skill_fail' => '-2',
            ],
            '22-24' => [
                'player' => 'RB3',
                'rating' => 'RUSH',
                'skill_pass' => '6 + R',
                'skill_fail' => '-1',
            ],
            '25-29' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '30' => [
                'player' => 'RB4',
                'rating' => 'RUSH',
                'skill_pass' => '5 + R',
                'skill_fail' => '1',
            ],
            '31-34' => [
                'player' => 'OL',
                'rating' => 'RUSH',
                'skill_pass' => '4',
                'skill_fail' => '0',
            ],
            '35-39' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '40-42' => [
                'player' => 'OL',
                'rating' => 'RUSH',
                'skill_pass' => 'B!',
                'skill_fail' => '-2',
            ],
            '43-45' => [
                'player' => 'DL1',
                'rating' => 'TACKLE',
                'skill_pass' => '0',
                'skill_fail' => '5',
            ],
            '46-47' => [
                'player' => 'DL2',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => 'B!',
            ],
            '48' => [
                'player' => 'DL3',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '10',
            ],
            '49-50' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '13',
            ],
            '51-54' => [
                'player' => 'LB2',
                'rating' => 'TACKLE',
                'skill_pass' => '-3',
                'skill_fail' => '13',
            ],
            '55-56' => [
                'player' => 'LB3',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '8',
            ],
            '57-58' => [
                'player' => 'LB4',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => 'B!',
            ],
            '59-60' => [
                'player' => 'S1',
                'rating' => 'TACKLE',
                'skill_pass' => '2',
                'skill_fail' => '9',
            ],
            '61-62' => [
                'player' => 'S2',
                'rating' => 'TACKLE',
                'skill_pass' => '3',
                'skill_fail' => '14',
            ],
            '63-64' => [
                'player' => 'LB2',
                'rating' => 'STRIP',
                'skill_pass' => 'FF 5',
                'skill_fail' => '9',
            ],
            '65-68' => [
                'player' => 'AUTO',
                'rating' => 'REDZONE',
                'skill_pass' => '11',
                'skill_fail' => '-2',
            ],
            '69' => [
                'player' => 'AUTO',
                'rating' => 'HOME',
                'skill_pass' => '6',
                'skill_fail' => '1',
            ],
        ]
    ],
    'SC' => [
        'name' => 'Screen Play',
        'play_type' => 'PASS',
        'roll' => [
            '10' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '5',
                'skill_fail' => 'False Start',
            ],
            '11-13' => [
                'player' => 'RB1',
                'rating' => 'REC',
                'skill_pass' => '2 + R',
                'skill_fail' => 'INC',
            ],
            '14-15' => [
                'player' => 'RB2',
                'rating' => 'REC',
                'skill_pass' => '2 + R',
                'skill_fail' => 'INC',
            ],
            '16-17' => [
                'player' => 'RB3',
                'rating' => 'REC',
                'skill_pass' => '2 + R',
                'skill_fail' => 'INC',
            ],
            '18-19' => [
                'player' => 'RB4',
                'rating' => 'REC',
                'skill_pass' => '2 + R',
                'skill_fail' => 'INC',
            ],
            '20-22' => [
                'player' => 'WR1',
                'rating' => 'REC',
                'skill_pass' => '3 + R',
                'skill_fail' => 'INC',
            ],
            '23-24' => [
                'player' => 'WR2',
                'rating' => 'REC',
                'skill_pass' => '3 + R',
                'skill_fail' => 'INC',
            ],
            '25-30' => [
                'player' => 'QB1',
                'rating' => 'ACC',
                'skill_pass' => '5',
                'skill_fail' => 'INC',
            ],
            '31-32' => [
                'player' => 'OL',
                'rating' => 'PASS',
                'skill_pass' => '9',
                'skill_fail' => '-1',
            ],
            '33-36' => [
                'player' => 'OL',
                'rating' => 'PASS',
                'skill_pass' => 'B!',
                'skill_fail' => '2',
            ],
            '37-38' => [
                'player' => 'LB1',
                'rating' => 'TACKLE',
                'skill_pass' => '1',
                'skill_fail' => '11',
            ],
            '39' => [
                'player' => 'LB2',
                'rating' => 'TACKLE',
                'skill_pass' => '0',
                'skill_fail' => '8',
            ],
            '40-44' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '45' => [
                'player' => 'LB3',
                'rating' => 'TACKLE',
                'skill_pass' => '-2',
                'skill_fail' => '6',
            ],
            '46-49' => [
                'player' => 'CB1',
                'rating' => 'TACKLE',
                'skill_pass' => '-3',
                'skill_fail' => '10',
            ],
            '50-54' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '55-58' => [
                'player' => 'CB2',
                'rating' => 'TACKLE',
                'skill_pass' => '-1',
                'skill_fail' => '12',
            ],
            '59-60' => [
                'player' => 'S2',
                'rating' => 'TACKLE',
                'skill_pass' => '4',
                'skill_fail' => 'B!',
            ],
            '63-64' => [
                'player' => 'AUTO',
                'rating' => 'REDZONE',
                'skill_pass' => '3 + R',
                'skill_fail' => 'INC',
            ],
            '65-68' => [
                'player' => 'AUTO',
                'rating' => 'REDZONE',
                'skill_pass' => '1 + R',
                'skill_fail' => 'PRESSURE',
            ],
            '69' => [
                'player' => 'AUTO',
                'rating' => 'HOME',
                'skill_pass' => '7',
                'skill_fail' => 'INC',
            ],
        ]
    ],
    'SP' => [
        'name' => 'Short Pass',
        'play_type' => 'PASS',
        'roll' => [
            '10' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '5',
                'skill_fail' => 'False Start',
            ],
            '11' => [
                'player' => 'RB1',
                'rating' => 'REC',
                'skill_pass' => '6 + R',
                'skill_fail' => 'INC',
            ],
            '12' => [
                'player' => 'RB2',
                'rating' => 'REC',
                'skill_pass' => '6 + R',
                'skill_fail' => 'INC',
            ],
            '13' => [
                'player' => 'RB3',
                'rating' => 'REC',
                'skill_pass' => '6 + R',
                'skill_fail' => 'INC',
            ],
            '14-17' => [
                'player' => 'TE1',
                'rating' => 'REC',
                'skill_pass' => '6 + R',
                'skill_fail' => 'INC',
            ],
            '18-19' => [
                'player' => 'TE2',
                'rating' => 'REC',
                'skill_pass' => '6 + R',
                'skill_fail' => 'INC',
            ],
            '20-22' => [
                'player' => 'WR1',
                'rating' => 'REC',
                'skill_pass' => '7 + R',
                'skill_fail' => 'INC',
            ],
            '23-30' => [
                'player' => 'WR2',
                'rating' => 'REC',
                'skill_pass' => '7 + R',
                'skill_fail' => 'INC',
            ],
            '26-27' => [
                'player' => 'WR3',
                'rating' => 'REC',
                'skill_pass' => '7 + R',
                'skill_fail' => 'INC',
            ],
            '28' => [
                'player' => 'WR4',
                'rating' => 'REC',
                'skill_pass' => '7 + R',
                'skill_fail' => 'INC',
            ],
            '29-36' => [
                'player' => 'QB1',
                'rating' => 'ACC',
                'skill_pass' => '4 + R',
                'skill_fail' => 'INC',
            ],
            '37' => [
                'player' => 'QB1',
                'rating' => 'CTRL',
                'skill_pass' => '7',
                'skill_fail' => 'INT 8',
            ],
            '38-42' => [
                'player' => 'OL',
                'rating' => 'PROTECT',
                'skill_pass' => '8',
                'skill_fail' => 'PRESSURE',
            ],
            '43-44' => [
                'player' => 'DL1',
                'rating' => 'SACK',
                'skill_pass' => 'SK 6',
                'skill_fail' => '9',
            ],
            '45-54' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '55-56' => [
                'player' => 'CB1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => 'B!',
            ],
            '57-58' => [
                'player' => 'CB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '11',
            ],
            '59-60' => [
                'player' => 'LB3',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '10',
            ],
            '63-64' => [
                'player' => 'AUTO',
                'rating' => 'REDZONE',
                'skill_pass' => '6 + R',
                'skill_fail' => 'INC',
            ],
            '65-68' => [
                'player' => 'AUTO',
                'rating' => 'REDZONE',
                'skill_pass' => '4 + R',
                'skill_fail' => 'PRESSURE',
            ],
            '69' => [
                'player' => 'AUTO',
                'rating' => 'HOME',
                'skill_pass' => '10',
                'skill_fail' => 'PRESSURE',
            ],
        ]
    ],
    'MP' => [
        'name' => 'Medium Pass',
        'play_type' => 'PASS',
        'roll' => [
            '10' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '5',
                'skill_fail' => 'False Start',
            ],
            '11' => [
                'player' => 'PENALITY',
                'rating' => 'DEF',
                'skill_pass' => '12 + R',
                'skill_fail' => 'Pass Interference',
            ],
            '12-13' => [
                'player' => 'WR1',
                'rating' => 'RDEEP',
                'skill_pass' => '17',
                'skill_fail' => 'INC',
            ],
            '14-15' => [
                'player' => 'TE1',
                'rating' => 'RDEEP',
                'skill_pass' => '15',
                'skill_fail' => 'INC',
            ],
            '16' => [
                'player' => 'TE2',
                'rating' => 'REC',
                'skill_pass' => '14',
                'skill_fail' => 'INC',
            ],
            '17-19' => [
                'player' => 'QB1',
                'rating' => 'PDEEP',
                'skill_pass' => '18',
                'skill_fail' => 'INC',
            ],
            '20-22' => [
                'player' => 'WR1',
                'rating' => 'REC',
                'skill_pass' => '10 + R',
                'skill_fail' => 'INC',
            ],
            '23-24' => [
                'player' => 'WR2',
                'rating' => 'REC',
                'skill_pass' => '12 + R',
                'skill_fail' => 'INC',
            ],
            '25-27' => [
                'player' => 'QB1',
                'rating' => 'ACC',
                'skill_pass' => '10',
                'skill_fail' => 'INC',
            ],
            '28-29' => [
                'player' => 'QB1',
                'rating' => 'CTRL',
                'skill_pass' => 'INC',
                'skill_fail' => 'INT 14',
            ],
            '30-38' => [
                'player' => 'OL',
                'rating' => 'PROTECT',
                'skill_pass' => '10 + R',
                'skill_fail' => 'PRESSURE',
            ],
            '39-41' => [
                'player' => 'DL2',
                'rating' => 'SACK',
                'skill_pass' => 'SK 5',
                'skill_fail' => '13',
            ],
            '42-44' => [
                'player' => 'DL3',
                'rating' => 'SACK',
                'skill_pass' => 'SK 9',
                'skill_fail' => 'INC',
            ],
            '45-46' => [
                'player' => 'LB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '11',
            ],
            '47' => [
                'player' => 'S1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '23',
            ],
            '57-58' => [
                'player' => 'S2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '26',
            ],
            '50-59' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '59-60' => [
                'player' => 'CB1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '16',
            ],
            '62-63' => [
                'player' => 'CB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '10 + B!',
            ],
            '64-68' => [
                'player' => 'AUTO',
                'rating' => 'REDZONE',
                'skill_pass' => '10 + R',
                'skill_fail' => 'PRESSURE',
            ],
            '69' => [
                'player' => 'AUTO',
                'rating' => 'HOME',
                'skill_pass' => '15',
                'skill_fail' => 'PRESSURE',
            ],
        ]
    ],
    'LP' => [
        'name' => 'Long Pass',
        'play_type' => 'PASS',
        'roll' => [
            '10' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '5',
                'skill_fail' => 'False Start',
            ],
            '11' => [
                'player' => 'PENALITY',
                'rating' => 'DEF',
                'skill_pass' => '22 + R',
                'skill_fail' => 'Pass Interference',
            ],
            '12' => [
                'player' => 'PENALITY',
                'rating' => 'DEF',
                'skill_pass' => '32',
                'skill_fail' => 'Pass Interference',
            ],
            '13' => [
                'player' => 'WR1',
                'rating' => 'RDEEP',
                'skill_pass' => '28',
                'skill_fail' => 'INC',
            ],
            '14-17' => [
                'player' => 'WR2',
                'rating' => 'RDEEP',
                'skill_pass' => '27',
                'skill_fail' => 'INC',
            ],
            '18-19' => [
                'player' => 'WR3',
                'rating' => 'RDEEP',
                'skill_pass' => '25',
                'skill_fail' => 'INC',
            ],
            '20-24' => [
                'player' => 'QB1',
                'rating' => 'PDEEP',
                'skill_pass' => '20 + B!',
                'skill_fail' => 'INC',
            ],
            '25-27' => [
                'player' => 'QB1',
                'rating' => 'CTRL',
                'skill_pass' => 'INC',
                'skill_fail' => 'INT 19',
            ],
            '28-30' => [
                'player' => 'OL',
                'rating' => 'PROTECT',
                'skill_pass' => 'INC',
                'skill_fail' => 'PRESSURE',
            ],
            '31-42' => [
                'player' => 'OL',
                'rating' => 'PROTECT',
                'skill_pass' => '20 + R',
                'skill_fail' => 'PRESSURE',
            ],
            '43-46' => [
                'player' => 'DL4',
                'rating' => 'SACK',
                'skill_pass' => 'SK 10',
                'skill_fail' => 'INC',
            ],
            '47-49' => [
                'player' => 'LB1',
                'rating' => 'SACK',
                'skill_pass' => 'SK 13',
                'skill_fail' => 'INC',
            ],
            '50-54' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '45-56' => [
                'player' => 'CB1',
                'rating' => 'INT',
                'skill_pass' => 'INT 29',
                'skill_fail' => 'INC',
            ],
            '57' => [
                'player' => 'CB2',
                'rating' => 'INT',
                'skill_pass' => 'INT 26',
                'skill_fail' => 'INC',
            ],
            '58' => [
                'player' => 'CB1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '24',
            ],
            '59' => [
                'player' => 'CB2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '21',
            ],
            '60-54' => [
                'player' => 'DEF',
                'rating' => 'N/A',
                'skill_pass' => 'N/A',
                'skill_fail' => 'N/A',
            ],
            '66-66' => [
                'player' => 'S1',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '30',
            ],
            '67-68' => [
                'player' => 'S2',
                'rating' => 'COVER',
                'skill_pass' => 'INC',
                'skill_fail' => '33',
            ],
            '69' => [
                'player' => 'AUTO',
                'rating' => 'HOME',
                'skill_pass' => 'INC',
                'skill_fail' => 'INT 25',
            ],
        ]
    ],
    'PRESSURE' => [
        'name' => 'Pressure',
        'play_type' => 'PASS',
        'roll' => [
            '10' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '10',
                'skill_fail' => 'Intentional Grounding',
            ],
            '11' => [
                'player' => 'PENALITY',
                'rating' => 'OFF',
                'skill_pass' => '10 + R',
                'skill_fail' => 'Intentional Grounding',
            ],
            '12-18' => [
                'player' => 'QB1',
                'rating' => 'EVADE',
                'skill_pass' => 'B!',
                'skill_fail' => 'SK 7',
            ],
            '19-23' => [
                'player' => 'QB1',
                'rating' => 'EVADE',
                'skill_pass' => 'INC',
                'skill_fail' => 'SK 11',
            ],
            '24-29' => [
                'player' => 'QB1',
                'rating' => 'RUSH',
                'skill_pass' => '1 + R',
                'skill_fail' => 'SK 5',
            ],
            '30-39' => [
                'player' => 'QB1',
                'rating' => 'RUSH',
                'skill_pass' => 'B!',
                'skill_fail' => 'SK 2',
            ],
            '40-43' => [
                'player' => 'QB1',
                'rating' => 'CTRL',
                'skill_pass' => 'INC',
                'skill_fail' => 'INT 13',
            ],
            '44-45' => [
                'player' => 'DL1',
                'rating' => 'SACK',
                'skill_pass' => 'SK 9',
                'skill_fail' => 'INC',
            ],
            '46-47' => [
                'player' => 'DL2',
                'rating' => 'SACK',
                'skill_pass' => 'SK 10',
                'skill_fail' => 'INC',
            ],
            '48-49' => [
                'player' => 'DL3',
                'rating' => 'SACK',
                'skill_pass' => 'SK 6',
                'skill_fail' => '11',
            ],
            '50-51' => [
                'player' => 'DL4',
                'rating' => 'SACK',
                'skill_pass' => 'SK 7',
                'skill_fail' => '10',
            ],
            '52-53' => [
                'player' => 'LB1',
                'rating' => 'SACK',
                'skill_pass' => 'SK 4',
                'skill_fail' => '13',
            ],
            '54-55' => [
                'player' => 'LB2',
                'rating' => 'SACK',
                'skill_pass' => 'SK 8',
                'skill_fail' => 'INC',
            ],
            '56-57' => [
                'player' => 'LB3',
                'rating' => 'SACK',
                'skill_pass' => 'SK 12',
                'skill_fail' => 'INC',
            ],
            '58-59' => [
                'player' => 'LB4',
                'rating' => 'SACK',
                'skill_pass' => 'SK 14',
                'skill_fail' => 'INC',
            ],
            '60-61' => [
                'player' => 'CB1',
                'rating' => 'INT',
                'skill_pass' => 'INT 11',
                'skill_fail' => 'INC',
            ],
            '62-63' => [
                'player' => 'CB2',
                'rating' => 'INT',
                'skill_pass' => 'INT 15',
                'skill_fail' => 'INC',
            ],
            '64-66' => [
                'player' => 'S1',
                'rating' => 'INT',
                'skill_pass' => 'INT 25',
                'skill_fail' => 'INC',
            ],
            '67-69' => [
                'player' => 'S2',
                'rating' => 'INT',
                'skill_pass' => 'INT 30',
                'skill_fail' => 'INC',
            ],
        ]
    ],
];
